Feature add thing action
AnthonyRedGrave/collect_service pull request #5
Opened 2021-07-08 14:07 UTC by AnthonyRedGrave

2021-07-08 14:51 UTC, mortalfc requested changes

2021-07-08 14:51 UTC, mortalfc commented on collect_service/collect_api/views.py
> +            ThingMessage.objects.create(content = request.data['content'],
сериализаторы нужны для того, что бы валидировать и обрабатывать данные, зачем нам сериалайзер если мы прям из запроса все берем?? это надо вытащить из сериалайзера

2021-07-08 15:26 UTC, AnthonyRedGrave commented on collect_service/collect_api/tests/views/test_thing_views.py
> -
так вышло(

2021-07-08 15:26 UTC, AnthonyRedGrave commented on collect_service/collect_api/views.py
> +            return JsonResponse(thing.get_messages, safe=False)
Все еще не уверен, что это хорошая идея. Также необходимо убрать serializer, он уже не нужен

2021-07-12 08:35 UTC, mortalfc approved these changes

2021-07-12 08:35 UTC, mortalfc commented on collect_service/collect_api/views.py
> +                ThingMessage.objects.create(content = thing_message_serializer.validated_data['content'],
thing.messages.add(**{
"content" : thing_message_serializer.validated_data['content'],
user=thing_message_serializer.validated_data['user'],
thing = thing_message_serializer.validated_data['thing']
})

2021-07-12 08:35 UTC, merged